## YAML Template.
spring:
  application:
    name: tqueue

  datasource:
    url: jdbc:postgresql://localhost:5432/tqueue
    username: postgres
    password: root
  
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#  
#logging:
#    level: 
#        org:
#          springframework:
#            web: DEBUG